<a href="https://colab.research.google.com/github/vuchicago/Python/blob/master/Price_elasticity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
####MOUNT DRIVE
from google.colab import drive
drive.mount('/content/gdrive',force_remount=True)

Mounted at /content/gdrive

In [2]:
##strategy, tactics, analysis, review (STAR 2024)
import os
import pandas as pd
import numpy as np
import matplotlib as mpl
from matplotlib import pyplot as plt
from datetime import datetime as dt

base_dir="/content/gdrive/My Drive/Python/Price_Elasticity"
os.chdir(base_dir)

In [3]:
df=pd.read_csv("Price_elasticity_2019.csv")

In [3]:
df["Rev@Stat - TO"].astype(float)

0         111.33
1         121.25
2          94.80
3          99.21
4          99.21
           ...
595837    128.68
595838    138.29
595839    131.66
595840    161.99
595841    161.98
Name: Rev@Stat - TO, Length: 595842, dtype: float64

In [4]:
ind_var=[
 'Jan',
 'Feb',
 'Mar',
 'Apr',
 'May',
 'Jun',
 'Jul',
 'Aug',
 'Sep',
 'Oct',
 'Nov',
 'Dec',
 'PORTLAND, TYPE I/II LSA',
 'PORTLAND,TYPE I,LOW ALKALI LSA',
 'PORTLAND,TYPE I/II,LOW ALKALI LSA',
 'PORTLAND,TYPE IA',
 'PORTLAND,TYPE I/II, LOW ALKALI',
 'PORTLAND,TYPE III',
 'PORTLAND,TYPE I/II/GU/MS',
 'CEMENT,REMEDIATION',
 'PORTLAND, TYPE GU',
 'PORTLAND, TYPE HE',
 'PORTLAND,TYPE V LSA/HS',
 'PORTLAND,TYPE II V/HS',
 'API CLASS A OILWELL (O)',
 'API CLASS H OILWELL (HSR)',
 #'CEMENT TYPE ONECEM LD 12.0 LAF',
 'PORTLAND, TYPE GU (P)',
 'API CLASS G OILWELL (HSR)-CA',
 'PORTLAND, TYPE GU - L',
 'PORTLAND TYPE GU-P LA',
 'API CLASS H OILWELL (HSR) BIG BAG',
 'PORTLAND,AASHTO II',
 'PORTLAND,TYPE II-V',
 'PORTLAND TYPE I ENHANCED',
 'PORTLAND,TYPE I']

dep_var='Rev@Stat - TO'
vol= 'Volume - TO'

In [6]:
df.head()

  Terminal                 Material  ... PORTLAND TYPE I ENHANCED PORTLAND,TYPE I
0      ADA  PORTLAND, TYPE I/II LSA  ...                      0.0             0.0
1      ADA  PORTLAND, TYPE I/II LSA  ...                      0.0             0.0
2      ADA  PORTLAND, TYPE I/II LSA  ...                      0.0             0.0
3      ADA  PORTLAND, TYPE I/II LSA  ...                      0.0             0.0
4      ADA  PORTLAND, TYPE I/II LSA  ...                      0.0             0.0

[5 rows x 43 columns]

In [5]:
###########CORRELATION BETWEEN VARIABLES AND PRICE
from scipy.stats.stats import pearsonr
from matplotlib import pyplot as plt

In [8]:
a=print("Volume = ", pearsonr(df[vol].astype(float),df[dep_var].astype(float)))
corr=pd.DataFrame()
pd.concat([corr,a])
for i in ind_var:
  a=print(i," = ",pearsonr(df[i].astype(float),df[dep_var].astype(float)))
  a=pd.DataFrame(a)
corr=pd.concat([corr,a])

Volume =  (-0.004097393115638937, 0.001562503733453008)
Jan  =  (-0.008060185341521857, 4.914527366464352e-10)
Feb  =  (-0.008019567857924665, 5.999066373900993e-10)
Mar  =  (-0.010810771562898515, 7.112495923317502e-17)
Apr  =  (-0.0002260389971374478, 0.8614874985307236)
May  =  (0.003796071335212214, 0.0033871955154167748)
Jun  =  (0.0048963647112611, 0.00015710703257384016)
Jul  =  (0.006464704396290773, 6.031715972493997e-07)
Aug  =  (0.0011468426958399173, 0.3760188365143559)
Sep  =  (0.0060375900186501906, 3.154469336793856e-06)
Oct  =  (0.003745090055153566, 0.0038417805049597437)
Nov  =  (-0.003997367073209924, 0.002031380909344209)
Dec  =  (-0.0024534336373481153, 0.058248375960147966)
PORTLAND, TYPE I/II LSA  =  (-0.05980305610301583, 0.0)
PORTLAND,TYPE I,LOW ALKALI LSA  =  (0.031434003768335744, 4.0564745728773504e-130)
PORTLAND,TYPE I/II,LOW ALKALI LSA  =  (-0.02729887137537281, 1.3180440377327246e-98)
PORTLAND,TYPE IA  =  (-0.004771043610186713, 0.00023066796127094755)
PORTLAND,TYPE I/II, LOW ALKALI  =  (0.04008290609338361, 2.337447277599661e-210)
PORTLAND,TYPE III  =  (0.029076197653386954, 1.3132785919101601e-111)
PORTLAND,TYPE I/II/GU/MS  =  (-0.0035888981264351315, 0.005600427433513451)
CEMENT,REMEDIATION  =  (-0.013025475917505415, 8.743248910000553e-24)
PORTLAND, TYPE GU  =  (0.04057285396044098, 1.7467243348555595e-215)
PORTLAND, TYPE HE  =  (0.022395432502892686, 5.659064105401677e-67)
PORTLAND,TYPE V LSA/HS  =  (0.027092791880084344, 3.754542109306183e-97)
PORTLAND,TYPE II V/HS  =  (0.007337722329744092, 1.4778861925412104e-08)
API CLASS A OILWELL (O)  =  (0.01704651221813823, 1.5053714497373993e-39)
API CLASS H OILWELL (HSR)  =  (0.09485127389131065, 0.0)
PORTLAND, TYPE GU (P)  =  (-0.02567669005990504, 1.8752077264788224e-87)
API CLASS G OILWELL (HSR)-CA  =  (0.009091310714045772, 2.254114408511529e-12)
PORTLAND, TYPE GU - L  =  (0.01578242221868908, 3.8147207645717913e-34)
PORTLAND TYPE GU-P LA  =  (-0.004815935073762402, 0.00020122573074819904)
API CLASS H OILWELL (HSR) BIG BAG  =  (0.025790201284790943, 3.2716445687078413e-88)
PORTLAND,AASHTO II  =  (0.0010521549484317318, 0.4166967473172219)
PORTLAND,TYPE II-V  =  (0.010588731892191302, 2.989759756755629e-16)
PORTLAND TYPE I ENHANCED  =  (-0.01618077146260865, 8.374475408024814e-36)
PORTLAND,TYPE I  =  (-0.058892971937265795, 0.0)

In [9]:
df_new=df.sample(frac=1,random_state=3) ###Samples data with same random state
df_train=df_new[:np.int(.8*len(df_new))]
df_val=df_new[np.int(.8*len(df_new)):]

In [10]:
df_train.describe()

        Billing Doc    Volume - TO  ...  PORTLAND TYPE I ENHANCED  PORTLAND,TYPE I
count  4.766730e+05  476673.000000  ...             476673.000000    476673.000000
mean   8.786448e+09      24.839737  ...                  0.003308         0.014215
std    1.411653e+09      44.778053  ...                  0.057423         0.118377
min    2.900894e+08   -5002.000000  ...                  0.000000         0.000000
25%    9.031859e+09      23.000000  ...                  0.000000         0.000000
50%    9.033798e+09      24.000000  ...                  0.000000         0.000000
75%    9.035735e+09      24.000000  ...                  0.000000         0.000000
max    9.037818e+09    6492.000000  ...                  1.000000         1.000000

[8 rows x 39 columns]

In [11]:
############################################THE EFFECTS OF VOLUME ON PRICE GIVEN EACH VARIABLE IN THE DEP_VAR LIST training dataset
corr=pd.DataFrame()

for i in ind_var:
  df_train_var=df_train[df_train[i]==1]
  a=print("Effects of Vol on Price given Vol:",df_train_var[vol].sum()," and ",i," = ",pearsonr(df_train_var[vol].astype(float),df_train_var[dep_var].astype(float)))
  a=pd.DataFrame(a)
corr=pd.concat([corr,a])

Effects of Vol on Price given Vol: 609648.0  and  Jan  =  (-0.013815132636221215, 0.028955112917783837)
Effects of Vol on Price given Vol: 543401.0  and  Feb  =  (0.029668849881789167, 7.707063655102102e-06)
Effects of Vol on Price given Vol: 765090.0  and  Mar  =  (-0.005012513283879647, 0.3726645023239686)
Effects of Vol on Price given Vol: 992224.0  and  Apr  =  (-0.026328402855742, 1.3353384383186928e-07)
Effects of Vol on Price given Vol: 1134006.0  and  May  =  (-0.004935203007706586, 0.2962897794783895)
Effects of Vol on Price given Vol: 1096968.0  and  Jun  =  (-0.011718175599592071, 0.01453767794864826)
Effects of Vol on Price given Vol: 1229104.0  and  Jul  =  (-0.015981540130238364, 0.0003772864898458424)
Effects of Vol on Price given Vol: 1342245.0  and  Aug  =  (0.000293078758447393, 0.9467733536912893)
Effects of Vol on Price given Vol: 1259872.0  and  Sep  =  (-0.025039485146040777, 6.680982068414049e-09)
Effects of Vol on Price given Vol: 1253564.0  and  Oct  =  (-0.00590592691005833, 0.18918023351198995)
Effects of Vol on Price given Vol: 900602.0  and  Nov  =  (-0.004264888269386189, 0.41904509264145356)
Effects of Vol on Price given Vol: 713708.0  and  Dec  =  (-0.009867538257483613, 0.09514978216764003)
Effects of Vol on Price given Vol: 2595765.0  and  PORTLAND, TYPE I/II LSA  =  (-0.008136219607726152, 0.007398309830005429)
Effects of Vol on Price given Vol: 264540.0  and  PORTLAND,TYPE I,LOW ALKALI LSA  =  (0.09646718821270123, 5.556131997578081e-25)
Effects of Vol on Price given Vol: 3738667.0  and  PORTLAND,TYPE I/II,LOW ALKALI LSA  =  (-0.010003228850999742, 8.723925594875629e-05)
Effects of Vol on Price given Vol: 22694.0  and  PORTLAND,TYPE IA  =  (0.06283812470139986, 0.04534120157072254)
Effects of Vol on Price given Vol: 1947342.0  and  PORTLAND,TYPE I/II, LOW ALKALI  =  (-0.0357941332185727, 9.968766680964355e-21)
Effects of Vol on Price given Vol: 212384.0  and  PORTLAND,TYPE III  =  (-0.05387644878396829, 3.7695669435942745e-07)
Effects of Vol on Price given Vol: 1538850.0  and  PORTLAND,TYPE I/II/GU/MS  =  (0.12992958080858089, 2.3932118699195183e-261)
Effects of Vol on Price given Vol: 8933.0  and  CEMENT,REMEDIATION  =  (0.16094471480932507, 0.0006928640536326054)
Effects of Vol on Price given Vol: 409837.0  and  PORTLAND, TYPE GU  =  (-0.005469090274221801, 0.48325048970746964)
Effects of Vol on Price given Vol: 70760.0  and  PORTLAND, TYPE HE  =  (0.07625224888060472, 3.354684318693875e-05)
Effects of Vol on Price given Vol: 536635.0  and  PORTLAND,TYPE V LSA/HS  =  (-0.14958216437754324, 8.466018177448928e-72)
Effects of Vol on Price given Vol: 36000.0  and  PORTLAND,TYPE II V/HS  =  (-0.14772222831310378, 2.5926946280920464e-06)
Effects of Vol on Price given Vol: 60462.0  and  API CLASS A OILWELL (O)  =  (0.04559346143019105, 0.015964063313415825)
Effects of Vol on Price given Vol: 101828.0  and  API CLASS H OILWELL (HSR)  =  (0.05894536480265774, 4.463380896328561e-05)
Effects of Vol on Price given Vol: 57008.0  and  PORTLAND, TYPE GU (P)  =  (0.006752004192529269, 0.7653740041519522)
Effects of Vol on Price given Vol: 10339.0  and  API CLASS G OILWELL (HSR)-CA  =  (0.010242492372841553, 0.8275190533283159)
Effects of Vol on Price given Vol: 35269.0  and  PORTLAND, TYPE GU - L  =  (0.1404064395915475, 1.0696757755943204e-07)
Effects of Vol on Price given Vol: 1407.0  and  PORTLAND TYPE GU-P LA  =  (-0.2072771929509075, 0.12531619120964607)
Effects of Vol on Price given Vol: 2958.0  and  API CLASS H OILWELL (HSR) BIG BAG  =  (0.015287622611292198, 0.8390464010224891)
Effects of Vol on Price given Vol: 642.0  and  PORTLAND,AASHTO II  =  (0.15154718134358927, 0.44141039681719646)
Effects of Vol on Price given Vol: 1544.0  and  PORTLAND,TYPE II-V  =  (0.7410409073342628, 4.999272866803669e-13)
Effects of Vol on Price given Vol: 35038.0  and  PORTLAND TYPE I ENHANCED  =  (0.11153403976647547, 9.015749543118422e-06)
Effects of Vol on Price given Vol: 151513.0  and  PORTLAND,TYPE I  =  (0.1681976003181561, 3.5039737657694706e-44)

In [12]:
############################################THE EFFECTS OF VOLUME ON PRICE GIVEN EACH VARIABLE IN THE DEP_VAR LIST validation dataset
corr=pd.DataFrame()

for i in ind_var:
  df_val_var=df_val[df_val[i]==1]
  a=print("Effects of Vol on Price given Vol:",df_val_var[vol].sum()," and ",i," = ",pearsonr(df_val_var[vol].astype(float),df_val_var[dep_var].astype(float)))
  a=pd.DataFrame(a)
corr=pd.concat([corr,a])

Effects of Vol on Price given Vol: 152795.0  and  Jan  =  (-0.02991479365544396, 0.019160376110715333)
Effects of Vol on Price given Vol: 135837.0  and  Feb  =  (0.015226510914210963, 0.2510194071719287)
Effects of Vol on Price given Vol: 191719.0  and  Mar  =  (-0.004200458387053154, 0.7083898900247585)
Effects of Vol on Price given Vol: 261175.0  and  Apr  =  (-0.04454015673785696, 7.72035263603448e-06)
Effects of Vol on Price given Vol: 284591.0  and  May  =  (-0.012543241038014165, 0.18415598725840376)
Effects of Vol on Price given Vol: 269816.0  and  Jun  =  (0.0103542562212869, 0.28074944473918173)
Effects of Vol on Price given Vol: 301509.0  and  Jul  =  (-0.02991142333772378, 0.0009446016910902888)
Effects of Vol on Price given Vol: 332788.0  and  Aug  =  (-0.008110562266291777, 0.3507500392601695)
Effects of Vol on Price given Vol: 309246.0  and  Sep  =  (-0.009554417409260888, 0.26788496501208625)
Effects of Vol on Price given Vol: 311529.0  and  Oct  =  (-0.006014701493684691, 0.505152899964967)
Effects of Vol on Price given Vol: 228359.0  and  Nov  =  (0.004345504938689181, 0.6800954412887456)
Effects of Vol on Price given Vol: 182087.0  and  Dec  =  (-0.024652095434183896, 0.03792091333748854)
Effects of Vol on Price given Vol: 656471.0  and  PORTLAND, TYPE I/II LSA  =  (-0.10747283983843464, 2.6679938586185367e-71)
Effects of Vol on Price given Vol: 66063.0  and  PORTLAND,TYPE I,LOW ALKALI LSA  =  (0.10021063250253284, 8.236157075743638e-08)
Effects of Vol on Price given Vol: 938174.0  and  PORTLAND,TYPE I/II,LOW ALKALI LSA  =  (-0.00658882314684045, 0.19686885727235878)
Effects of Vol on Price given Vol: 5894.0  and  PORTLAND,TYPE IA  =  (0.2596224159151818, 2.2449052825079192e-05)
Effects of Vol on Price given Vol: 474999.0  and  PORTLAND,TYPE I/II, LOW ALKALI  =  (-0.02810264557293507, 0.0002786381311142082)
Effects of Vol on Price given Vol: 50968.0  and  PORTLAND,TYPE III  =  (0.046952991979470345, 0.030752282949092737)
Effects of Vol on Price given Vol: 389930.0  and  PORTLAND,TYPE I/II/GU/MS  =  (0.11920999282912373, 5.238154560855027e-57)
Effects of Vol on Price given Vol: 2231.0  and  CEMENT,REMEDIATION  =  (0.07036084238677931, 0.473553736071336)
Effects of Vol on Price given Vol: 102358.0  and  PORTLAND, TYPE GU  =  (-0.027755316539782922, 0.07482172377249495)
Effects of Vol on Price given Vol: 17245.0  and  PORTLAND, TYPE HE  =  (0.0099603492866896, 0.7877660273949493)
Effects of Vol on Price given Vol: 133904.0  and  PORTLAND,TYPE V LSA/HS  =  (-0.14048036433295827, 5.662739527868436e-17)
Effects of Vol on Price given Vol: 8834.0  and  PORTLAND,TYPE II V/HS  =  (-0.10555549350295156, 0.09653232818525234)
Effects of Vol on Price given Vol: 15105.0  and  API CLASS A OILWELL (O)  =  (0.030039175132258147, 0.426482500438743)
Effects of Vol on Price given Vol: 24422.0  and  API CLASS H OILWELL (HSR)  =  (0.00452134663408519, 0.8779039965619659)
Effects of Vol on Price given Vol: 14649.0  and  PORTLAND, TYPE GU (P)  =  (-0.01649260251891595, 0.7188174983304912)
Effects of Vol on Price given Vol: 2766.0  and  API CLASS G OILWELL (HSR)-CA  =  (0.017217157020567878, 0.856368086315046)
Effects of Vol on Price given Vol: 9334.0  and  PORTLAND, TYPE GU - L  =  (0.11957761794901896, 0.020717947303526375)
Effects of Vol on Price given Vol: 442.0  and  PORTLAND TYPE GU-P LA  =  (0.896254132779897, 1.1276268164791145e-06)
Effects of Vol on Price given Vol: 544.0  and  API CLASS H OILWELL (HSR) BIG BAG  =  (0.17959151805122706, 0.2806339556236229)
Effects of Vol on Price given Vol: 182.0  and  PORTLAND,AASHTO II  =  (0.39850627798071125, 0.32813900338036095)
Effects of Vol on Price given Vol: 424.0  and  PORTLAND,TYPE II-V  =  (0.2903995742764454, 0.2423965380654287)
Effects of Vol on Price given Vol: 9042.0  and  PORTLAND TYPE I ENHANCED  =  (0.04845766072276272, 0.3282867430433599)
Effects of Vol on Price given Vol: 37470.0  and  PORTLAND,TYPE I  =  (0.18276851043656228, 4.606060935462687e-14)

In [4]:
#####using statsmodels
import statsmodels.api as sm
import statsmodels.formula.api as smf
from statsmodels.discrete import discrete_model

#df_var=df[ind_var]
ind_var2=[
 #'Jan',
 'Feb',
 #'Mar',
 #'Apr',
 #'May',
 #'Jun',
 'Jul',
 #'Aug',
 #'Sep',
 #'Oct',
 'Nov',
 #'Dec',
 #'PORTLAND, TYPE I/II LSA',
 'PORTLAND,TYPE I,LOW ALKALI LSA',
 'PORTLAND,TYPE I/II,LOW ALKALI LSA',
 #'PORTLAND,TYPE IA',
 #'PORTLAND,TYPE I/II, LOW ALKALI',
 #'PORTLAND,TYPE III',
 #'PORTLAND,TYPE I/II/GU/MS',
 #'CEMENT,REMEDIATION',
 #'PORTLAND, TYPE GU',
 #'PORTLAND, TYPE HE',
 #'PORTLAND,TYPE V LSA/HS',
 #'PORTLAND,TYPE II V/HS',
 #'API CLASS A OILWELL (O)',
 #'API CLASS H OILWELL (HSR)',
 #'CEMENT TYPE ONECEM LD 12.0 LAF',
 #'PORTLAND, TYPE GU (P)',
 #'API CLASS G OILWELL (HSR)-CA',
 #'PORTLAND, TYPE GU - L',
 #'PORTLAND TYPE GU-P LA',
 #'API CLASS H OILWELL (HSR) BIG BAG',
 #'PORTLAND,AASHTO II',
 #'PORTLAND,TYPE II-V',
 #'PORTLAND TYPE I ENHANCED',
 #'PORTLAND,TYPE I'
]
dep_var='Rev@Stat - TO'
vol= 'Volume - TO'

df_var=df[ind_var2]
df_label=df[dep_var]

df_label_mat=np.matrix(df_label,float)
df_var_mat=np.matrix(df_var,float)

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [5]:
####################################Create OLS model to predict correlations between volume and price 
X=df_var
X=sm.add_constant(X)
y=df_label
model=smf.ols('y ~ X',data=df).fit()
results=model.predict(X)

In [6]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.002
Model:                            OLS   Adj. R-squared:                  0.002
Method:                 Least Squares   F-statistic:                     198.2
Date:                Tue, 22 Sep 2020   Prob (F-statistic):          7.46e-212
Time:                        22:05:48   Log-Likelihood:            -3.4901e+06
No. Observations:              595842   AIC:                         6.980e+06
Df Residuals:                  595836   BIC:                         6.980e+06
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     63.8738      0.074    859.137      0.000      63.728      64.020
X[0]          63.8738      0.074    859.137      0.000      63.728      64.020
X[1]          -2.9884      0.518     -5.774      0.000      -4.003      -1.974
X[2]           1.2421      0.363      3.421      0.001       0.530       1.954
X[3]          -1.1719      0.419     -2.800      0.005      -1.992      -0.352
X[4]          15.9289      0.722     22.061      0.000      14.514      17.344
X[5]          -4.3415      0.236    -18.383      0.000      -4.804      -3.879
===============================================================================
Omnibus:                  2803405.325   Durbin-Watson:                    1.634
Prob(Omnibus):                  0.000   Jarque-Bera (JB):   136295295601045.828
Skew:                        -173.852   Prob(JB):                          0.00
Kurtosis:                   74095.750   Cond. No.                      4.63e+15
===============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 5.95e-26. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [8]:
pd.DataFrame(model.params)

                   0
Intercept  63.873788
X[0]       63.873788
X[1]       -2.988446
X[2]        1.242135
X[3]       -1.171945
X[4]       15.928927
X[5]       -4.341510

In [30]:
###########PRICE ELASTICITY DEPENDING ON PRODUCT
a=pd.DataFrame()

for i in ind_var2:
  df_var=df[df[i]==1]
  X=df_var[vol]
  X=sm.add_constant(X)
  y=df_var[dep_var]
  model=smf.ols('y ~ X',data=df_var).fit()
  a=pd.concat([a,pd.DataFrame(model.params)],axis=1)
print(a)

                   0          0          0          0          0
Intercept  61.073511  64.274473  62.663266  67.160363  61.811996
X[0]       61.073511  64.274473  62.663266  67.160363  61.811996
X[1]        0.060327  -0.012565   0.004502   0.401671  -0.014371

In [28]:
a

                   0          0          0          0          0
Intercept  61.073511  64.274473  62.663266  67.160363  61.811996
X[0]       61.073511  64.274473  62.663266  67.160363  61.811996
X[1]        0.060327  -0.012565   0.004502   0.401671  -0.014371

In [29]:
model.params

Intercept    61.811996
X[0]         61.811996
X[1]         -0.014371
dtype: float64